# Generated by Django 5.0.6 on 2024-07-07 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project_store',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('supervisor', models.CharField(max_length=100)),
                ('tags', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=50)),
                ('open_to', models.CharField(max_length=200)),
                ('duration', models.CharField(max_length=50)),
                ('sponsor', models.CharField(max_length=100)),
                ('deadline', models.DateField()),
                ('budget', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='UserRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_type', models.CharField(choices=[('admin', 'Admin (DORD)'), ('dean', 'Dean'), ('staff', 'Staff'), ('faculty', 'Faculty of IITK'), ('researchScholar', 'Research Scholars of IITK'), ('sectionB', 'Section B companies'), ('siicCompanies', 'SIIC Incubated companies'), ('projectStaff', 'Project Staff')], max_length=20)),
                ('dord_number', models.CharField(blank=True, max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('firm_expertise', models.TextField(blank=True)),
                ('sector_expertise', models.CharField(max_length=100)),
                ('subsector_expertise', models.CharField(blank=True, max_length=100)),
                ('past_projects', models.TextField(blank=True)),
                ('gender', models.CharField(choices=[('female', 'Female'), ('male', 'Male'), ('other', 'Other')], max_length=10)),
                ('state', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('pincode', models.CharField(max_length=10)),
                ('course', models.CharField(blank=True, max_length=100)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
    ]
